"""panel button labels

An operator's custom label for a panel button, keyed by the built-in default
text. No row means the built-in label.


Revision ID: 0abecf673292
Revises: e424709629fd
Create Date: 2026-08-23 14:52:51.930946
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0abecf673292"
down_revision: str | None = "e424709629fd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "panel_buttons",
        sa.Column("default_text", sa.String(length=64), nullable=False),
        sa.Column("custom_text", sa.String(length=64), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("default_text", name=op.f("pk_panel_buttons")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("panel_buttons")
    # ### end Alembic commands ###
