"""premium checked marker

`is_premium` defaults to false, and a default is not a finding. Without knowing
whether Telegram was ever asked, an unchecked connection was reported as *not*
Premium — which is how a Premium account came to be told it was not. NULL here
means never asked, and the panel says so rather than guessing.


Revision ID: 1d8d29c890f0
Revises: e699b98b5c90
Create Date: 2026-08-23 11:48:14.683493
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1d8d29c890f0"
down_revision: str | None = "e699b98b5c90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_connections",
        sa.Column("premium_checked_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_connections", "premium_checked_at")
    # ### end Alembic commands ###
