"""access requests

Revision ID: 1f8b9b01bec2
Revises: 7aadb60f9968
Create Date: 2026-10-03 15:11:05.521092
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '1f8b9b01bec2'
down_revision: str | None = '7aadb60f9968'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='access_request_status'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_access_requests_decided_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_requests')),
    sa.UniqueConstraint('telegram_user_id', name=op.f('uq_access_requests_telegram_user_id'))
    )
    op.create_index('ix_access_requests_status', 'access_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_access_requests_status', table_name='access_requests')
    op.drop_table('access_requests')
    # Dropping the table leaves the enum type behind, and the next upgrade then
    # fails on CREATE TYPE. Autogenerate never writes this line, so every enum
    # added here has to remember it — the same fix as in the broadcasts
    # migration.
    op.execute("DROP TYPE IF EXISTS access_request_status")
