"""repeating broadcasts

An ad can now post again to the same groups after a set interval. NULL
`repeat_every_s` means post once and stop, which stays the default — repeating
is turned on deliberately, and the floor on the interval is what keeps it from
becoming the thing that gets an account banned.


Revision ID: 275125af6acc
Revises: 1d8d29c890f0
Create Date: 2026-08-23 12:58:50.089999
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "275125af6acc"
down_revision: str | None = "1d8d29c890f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("broadcasts", sa.Column("repeat_every_s", sa.Integer(), nullable=True))
    op.add_column(
        "broadcasts", sa.Column("repeat_count", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("broadcasts", sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("broadcasts", "next_run_at")
    op.drop_column("broadcasts", "repeat_count")
    op.drop_column("broadcasts", "repeat_every_s")
    # ### end Alembic commands ###
