"""telegram admin panel

Revision ID: 293e62a48ff8
Revises: cb8bef6d5622
Create Date: 2026-08-22 13:45:34.507057
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "293e62a48ff8"
down_revision: str | None = "cb8bef6d5622"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=True),
        sa.Column("connection_id", sa.Uuid(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("send_attempts", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["telegram_connections.id"],
            name=op.f("fk_admin_notifications_connection_id_telegram_connections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["forwarding_rules.id"],
            name=op.f("fk_admin_notifications_rule_id_forwarding_rules"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_admin_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_notifications")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_admin_notifications_dedupe_key")),
    )
    op.create_index(
        "ix_admin_notifications_unsent",
        "admin_notifications",
        ["created_at"],
        unique=False,
        postgresql_where="sent_at IS NULL",
    )
    op.add_column("users", sa.Column("telegram_user_id", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("telegram_username", sa.String(length=64), nullable=True))
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=True)
    op.create_unique_constraint(op.f("uq_users_telegram_user_id"), "users", ["telegram_user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_users_telegram_user_id"), "users", type_="unique")
    op.alter_column("users", "password_hash", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("users", "telegram_username")
    op.drop_column("users", "telegram_user_id")
    op.drop_index(
        "ix_admin_notifications_unsent",
        table_name="admin_notifications",
        postgresql_where="sent_at IS NULL",
    )
    op.drop_table("admin_notifications")
    # ### end Alembic commands ###
