"""no terms gate

The terms screen and its accept gate are gone at the operator's request, so the
timestamp that recorded acceptance has nothing left to record. The warnings the
screen carried that lived nowhere else moved to the screens where they apply.


Revision ID: 3186df8d37cf
Revises: 3c94f89af195
Create Date: 2026-08-24 16:54:44.356519
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3186df8d37cf"
down_revision: str | None = "3c94f89af195"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "terms_accepted_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "terms_accepted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
