"""archive scope per account

Revision ID: 3c94f89af195
Revises: e9c210736b69
Create Date: 2026-08-24 16:22:52.349318
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3c94f89af195"
down_revision: str | None = "e9c210736b69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings",
        sa.Column("archive_all_users", sa.Boolean(), server_default="true", nullable=False),
    )
    op.add_column("users", sa.Column("archive_ads", sa.Boolean(), nullable=True))
    op.drop_column("users", "is_operator")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_operator",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "archive_ads")
    op.drop_column("app_settings", "archive_all_users")
    # ### end Alembic commands ###
