"""publisher interest

Revision ID: 7521ad3a3d86
Revises: 0abecf673292
Create Date: 2026-08-23 16:10:24.693009
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7521ad3a3d86"
down_revision: str | None = "0abecf673292"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("publisher_interest_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "publisher_interest_at")
    # ### end Alembic commands ###
