"""button colour

Revision ID: 773a23885e8d
Revises: d5c4eba495e4
Create Date: 2026-08-25 00:22:24.920369
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "773a23885e8d"
down_revision: str | None = "d5c4eba495e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("panel_buttons", sa.Column("style", sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("panel_buttons", "style")
    # ### end Alembic commands ###
