"""discovered links

Revision ID: 7aadb60f9968
Revises: 773a23885e8d
Create Date: 2026-09-06 01:23:00.392829
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7aadb60f9968"
down_revision: str | None = "773a23885e8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discovered_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("connection_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("link_key", sa.String(length=64), nullable=False),
        sa.Column("times_seen", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("hidden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_title", sa.String(length=255), nullable=True),
        sa.Column("resolved_member_count", sa.Integer(), nullable=True),
        sa.Column("resolved_kind", sa.String(length=16), nullable=True),
        sa.Column("resolve_error_code", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["telegram_connections.id"],
            name=op.f("fk_discovered_links_connection_id_telegram_connections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_links")),
        sa.UniqueConstraint(
            "connection_id", "kind", "link_key", name="uq_discovered_links_connection_key"
        ),
    )
    op.create_index(
        "ix_discovered_links_connection_hidden",
        "discovered_links",
        ["connection_id", "hidden_at"],
        unique=False,
    )
    op.create_table(
        "discovered_link_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("link_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.Uuid(), nullable=False),
        sa.Column("times_seen", sa.Integer(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["telegram_chats.id"],
            name=op.f("fk_discovered_link_sources_chat_id_telegram_chats"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["discovered_links.id"],
            name=op.f("fk_discovered_link_sources_link_id_discovered_links"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_link_sources")),
        sa.UniqueConstraint("link_id", "chat_id", name="uq_discovered_link_sources_link_chat"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("discovered_link_sources")
    op.drop_index("ix_discovered_links_connection_hidden", table_name="discovered_links")
    op.drop_table("discovered_links")
    # ### end Alembic commands ###
