"""broadcast formatting entities

An ad kept only its plain text, so bold, links and premium emoji were lost
between composing it and posting it. Telegram describes all three as
"entities" — offsets into the text — and they are stored as sent rather than
re-derived from markup: markup cannot express a custom emoji at all, and
round-tripping through it corrupts any message containing a literal asterisk.


Revision ID: 8a7239bfd658
Revises: 16d1e7be2bd4
Create Date: 2026-08-23 10:58:34.243008
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8a7239bfd658"
down_revision: str | None = "16d1e7be2bd4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "broadcasts",
        sa.Column(
            "body_entities",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("broadcasts", "body_entities")
    # ### end Alembic commands ###
