"""archive via bot

Revision ID: be6cd3dd3431
Revises: f04f23472bdd
Create Date: 2026-08-24 13:31:17.010040
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "be6cd3dd3431"
down_revision: str | None = "f04f23472bdd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_settings", sa.Column("archive_bot_chat_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "archive_bot_chat_id")
    # ### end Alembic commands ###
