"""archive chat

Revision ID: c7ce8fbae73e
Revises: f1fe6278ca22
Create Date: 2026-08-24 12:12:02.678572
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c7ce8fbae73e"
down_revision: str | None = "f1fe6278ca22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_settings", sa.Column("archive_chat_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_app_settings_archive_chat_id_telegram_chats"),
        "app_settings",
        "telegram_chats",
        ["archive_chat_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_app_settings_archive_chat_id_telegram_chats"), "app_settings", type_="foreignkey"
    )
    op.drop_column("app_settings", "archive_chat_id")
    # ### end Alembic commands ###
