"""no roles page

The role picker and the publisher waitlist are gone at the operator's request,
so the timestamp that recorded interest in a side that was never built has
nothing left to record.


Revision ID: d5c4eba495e4
Revises: 3186df8d37cf
Create Date: 2026-08-24 20:44:51.867078
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d5c4eba495e4"
down_revision: str | None = "3186df8d37cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "publisher_interest_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "publisher_interest_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
