"""panel premium icons

One row per unicode emoji the panel draws, holding the custom-emoji document id
an operator extracted for it. Rows present = premium icons on. The ids are
Telegram documents, so extraction from a connected account is the only source.


Revision ID: e424709629fd
Revises: 275125af6acc
Create Date: 2026-08-23 14:32:44.091293
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e424709629fd"
down_revision: str | None = "275125af6acc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "panel_emoji",
        sa.Column("emoticon", sa.String(length=16), nullable=False),
        sa.Column("custom_emoji_id", sa.String(length=32), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("emoticon", name=op.f("pk_panel_emoji")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("panel_emoji")
    # ### end Alembic commands ###
