"""connection premium flag

Only a Telegram Premium account may send custom emoji. Without knowing which
accounts have it, an ad written with premium emoji arrives showing the fallback
characters and looks like a bug in this tool. The flag comes from Telegram on
sign-in and on every health check, so the panel can warn before sending rather
than after.


Revision ID: e699b98b5c90
Revises: 8a7239bfd658
Create Date: 2026-08-23 11:33:05.000456
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e699b98b5c90"
down_revision: str | None = "8a7239bfd658"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "telegram_connections",
        sa.Column("is_premium", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_connections", "is_premium")
    # ### end Alembic commands ###
