"""operator granted in the panel

Revision ID: e9c210736b69
Revises: be6cd3dd3431
Create Date: 2026-08-24 16:03:35.519076
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e9c210736b69"
down_revision: str | None = "be6cd3dd3431"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_operator", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_operator")
    # ### end Alembic commands ###
