"""chat description and size

Revision ID: f04f23472bdd
Revises: c7ce8fbae73e
Create Date: 2026-08-24 12:24:43.006911
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f04f23472bdd"
down_revision: str | None = "c7ce8fbae73e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("telegram_chats", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("telegram_chats", sa.Column("member_count", sa.Integer(), nullable=True))
    op.add_column(
        "telegram_chats", sa.Column("details_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telegram_chats", "details_synced_at")
    op.drop_column("telegram_chats", "member_count")
    op.drop_column("telegram_chats", "description")
    # ### end Alembic commands ###
