"""button icon id

Revision ID: f1fe6278ca22
Revises: 7521ad3a3d86
Create Date: 2026-08-23 17:55:09.707755
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f1fe6278ca22"
down_revision: str | None = "7521ad3a3d86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "panel_buttons", sa.Column("icon_custom_emoji_id", sa.String(length=32), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("panel_buttons", "icon_custom_emoji_id")
    # ### end Alembic commands ###
